-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
---@module 'hl'

local subMod = "SUPER"
local hyprMod = "CTRL+ALT"

local scripts = "~/.config/hypr/scripts"
local scratchpad = "~/Documents/temp-scratchpad.md"
local ss_output = "~/Pictures/Screenshots"
local roficalc = "rofi -show calc -modi calc -no-show-match -no-sort -terse| wl-copy"
local rofi_scripts = "~/.config/rofi"

-- My rules for setting new keybinds
-- 1. Keybinds modes:
--     a) [HyprMod + Right Hand]    (only Right Hand)
--     b) [subMod + Left Hand]      (Mouse with Left Hand)
-- 2. 
-- 3. 

-- hl.bind("Insert", hl.dsp.pass("^(Caps_Lock)$"))

-- Window Control
hl.bind(subMod .. " + C", hl.dsp.window.close())
hl.bind(subMod .. " + V", hl.dsp.window.float())
hl.bind(subMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(subMod .. " + F", hl.dsp.window.fullscreen())

hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + TAB", hl.dsp.window.alter_zorder({ mode = "top" }))

-- Minimizing windows
hl.bind(hyprMod .. " + UP",   hl.dsp.exec_cmd("~/.config/hypr/scripts/unminimize.sh"))
hl.bind(hyprMod .. " + DOWN", hl.dsp.window.move({ workspace = "special:shadow", follow = false }))


-- Applications
hl.bind(subMod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(subMod .. " + SHIFT + T", hl.dsp.exec_cmd("alacritty"))
hl.bind(subMod .. " + W", hl.dsp.exec_cmd("nmrs"))
hl.bind(subMod .. " + E", hl.dsp.exec_cmd("pkill rofi || rofi -modi \"emoji\" -show emoji"))
hl.bind(subMod .. " + R", hl.dsp.exec_cmd("kitty -e bash -c 'rfkill unblock bluetooth && bluetui'"))


-- Wallpaper
hl.bind(subMod .. " + B", hl.dsp.exec_cmd("kitty -e yazi ~/.config/hypr/wallpaper")) -- Choose using Yazi
hl.bind(subMod .. " + SHIFT + B", hl.dsp.exec_cmd("~/.config/hypr/scripts/wp_change.sh")) -- Random


-- Custom Scripts
hl.bind(subMod .. " + G", hl.dsp.exec_cmd("sh -c 'pkill gammastep || gammastep -O 3400&'")) -- 4200 even in waybar
hl.bind(subMod .. " + N", hl.dsp.exec_cmd("$file_manager"))
hl.bind(subMod .. " + grave", hl.dsp.exec_cmd("alacritty -T Scratchpad -e nvim ~/Documents/temp-scratchpad.md"))


-- Rofi Keybinds
hl.bind("ALT + SPACE", hl.dsp.exec_cmd("pkill rofi || rofi -modi \"drun\" -show drun"))
hl.bind("SUPER + period", hl.dsp.exec_cmd("pkill rofi || rofi -modi \"emoji\" -show emoji"))
hl.bind(subMod .. " + Q", hl.dsp.exec_cmd("pkill rofi || rofi -show calc -modi calc -no-show-match -no-sort -terse| wl-copy"))
-- bind = $subMod, W,    exec, $rofi_scripts/rofi-wifi-menu.sh
hl.bind(subMod .. " + H", hl.dsp.exec_cmd("~/.config/rofi/rofi-clipboard.sh"))
hl.bind(hyprMod .. " + P", hl.dsp.exec_cmd("~/.config/rofi/rofi-powermenu.sh"))

-- Screenshots
hl.bind(subMod .. " + S", hl.dsp.exec_cmd("hyprshot -o ~/Pictures/Screenshots -z --mode output --mode active"))
hl.bind(subMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -o ~/Pictures/Screenshots -z --mode region"))
hl.bind(subMod .. " + CTRL + S", hl.dsp.exec_cmd("hyprshot -o ~/Pictures/Screenshots -z --mode window --mode active"))

-- ALT + Function Key

hl.bind("ALT + F1", hl.dsp.exec_cmd("pkill waybar || waybar&"))
-- bind = ALT, F2,
-- bind = ALT, F3,
hl.bind("ALT + F4", hl.dsp.window.close())

-- -- SUB + ARROW KEYS
-- hl.bind(subMod.."+LEFT" , hl.dsp.focus({ direction = "l" }))
-- hl.bind(subMod.."+DOWN" , hl.dsp.focus({ direction = "d" }))
-- hl.bind(subMod.."+UP"   , hl.dsp.focus({ direction = "u" }))
-- hl.bind(subMod.."+RIGHT", hl.dsp.focus({ direction = "r" }))
--
-- hl.bind(subMod.."+CTRL+LEFT" , hl.dsp.move({ direction = "l" }))
-- hl.bind(subMod.."+CTRL+DOWN" , hl.dsp.move({ direction = "d" }))
-- hl.bind(subMod.."+CTRL+UP"   , hl.dsp.move({ direction = "u" }))
-- hl.bind(subMod.."+CTRL+RIGHT", hl.dsp.move({ direction = "r" }))
--
-- hl.bind(subMod.."+SHIFT+LEFT" , hl.dsp.resize({-20,  0}))
-- hl.bind(subMod.."+SHIFT+DOWN" , hl.dsp.resize({  0, 20}))
-- hl.bind(subMod.."+SHIFT+UP"   , hl.dsp.resize({  0,-20}))
-- hl.bind(subMod.."+SHIFT+RIGHT", hl.dsp.resize({ 20,  0}))
--
-- -- SUB + VIM KEYS
-- hl.bind(subMod.."+H", hl.dsp.focus({ direction = "l" }))
-- hl.bind(subMod.."+J", hl.dsp.focus({ direction = "d" }))
-- hl.bind(subMod.."+K", hl.dsp.focus({ direction = "u" }))
-- hl.bind(subMod.."+L", hl.dsp.focus({ direction = "r" }))
--
-- hl.bind(subMod.."+CTRL+H", hl.dsp.move({ direction = "l" }))
-- hl.bind(subMod.."+CTRL+J", hl.dsp.move({ direction = "d" }))
-- hl.bind(subMod.."+CTRL+K", hl.dsp.move({ direction = "u" }))
-- hl.bind(subMod.."+CTRL+L", hl.dsp.move({ direction = "r" }))
--
-- hl.bind(subMod.."+SHIFT+H", hl.dsp.resize({-20,  0}))
-- hl.bind(subMod.."+SHIFT+J", hl.dsp.resize({  0, 20}))
-- hl.bind(subMod.."+SHIFT+K", hl.dsp.resize({  0,-20}))
-- hl.bind(subMod.."+SHIFT+L", hl.dsp.resize({ 20,  0}))

local navMap = {
	{ keys = { "LEFT",  "H" }, dir = "l", size = { x= -20, y=   0 } },
	{ keys = { "DOWN",  "J" }, dir = "d", size = { x=   0, y=  20 } },
	{ keys = { "UP",    "K" }, dir = "u", size = { x=   0, y= -20 } },
	{ keys = { "RIGHT", "L" }, dir = "r", size = { x=  20, y=   0 } },
}

for _, item in ipairs(navMap) do
	-- First, key = <arrow key>, then key = <vim key>
	for _, key in ipairs(item.keys) do
		hl.bind(subMod .. "+" .. key, hl.dsp.focus({ direction = item.dir }))
		hl.bind(subMod .. "+CTRL+" .. key, hl.dsp.window.move({ direction = item.dir }))
		hl.bind(subMod .. "+SHIFT+" .. key, hl.dsp.window.resize(item.size))
	end
end

-- SUB + NUMBER
-- hl.bind(subMod.."+1", hl.dsp.focus({ workspace = "e~1" }))
-- hl.bind(subMod.."+2", hl.dsp.focus({ workspace = "e~2" }))
-- hl.bind(subMod.."+3", hl.dsp.focus({ workspace = "e~3" }))
-- hl.bind(subMod.."+4", hl.dsp.focus({ workspace = "e~4" }))
-- hl.bind(subMod.."+5", hl.dsp.focus({ workspace = "e~5" }))
--
-- hl.bind(subMod.."+SHIFT+1", hl.dsp.window.move({ direction = "e~1" }))
-- hl.bind(subMod.."+SHIFT+2", hl.dsp.window.move({ direction = "e~2" }))
-- hl.bind(subMod.."+SHIFT+3", hl.dsp.window.move({ direction = "e~3" }))
-- hl.bind(subMod.."+SHIFT+4", hl.dsp.window.move({ direction = "e~4" }))
-- hl.bind(subMod.."+SHIFT+5", hl.dsp.window.move({ direction = "e~5" }))

for n = 1, 5 do
	-- Switch to n-th workspace
	hl.bind(subMod .. " + " .. n, hl.dsp.focus({ workspace = "e~" .. n }))
	-- Move active window to n-th workspace
	hl.bind(subMod .. " + SHIFT + " .. n, hl.dsp.window.move({ workspace = "e~" .. n }))
end

-- HYPR + LEFT/RIGHT
hl.bind(hyprMod .. " + LEFT", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(hyprMod .. " + RIGHT", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(hyprMod .. " + SHIFT + LEFT", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(hyprMod .. " + SHIFT + RIGHT", hl.dsp.window.move({ workspace = "e+1" }))


-- Resize window using Mod Key

-- Example special workspace (scratchpad)
-- bind = $subMod, S, togglespecialworkspace, magic
-- bind = $subMod SHIFT, S, movetoworkspace, special:magic


-- Scroll through existing workspaces with mainMod + scroll
hl.bind(subMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(subMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))


-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(subMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(subMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })


-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/hypr/scripts/control.sh V_MUTE"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/control.sh V_DOWN"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/control.sh V_UP"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.config/hypr/scripts/control.sh B_DOWN"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.config/hypr/scripts/control.sh B_UP"), { locked = true })
hl.bind("XF86TouchpadToggle", hl.dsp.exec_cmd("notify-send \"Please Fix F6\""), { locked = true })
hl.unbind("XF86Launch1")
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })


-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
