[mgr]    # Manager
show_hidden = true

[opener]
wp = [
	{ run = '/home/riff/.config/hypr/scripts/wp_change.sh %s', desc = "Change wallpaper", for = "linux" }
]

[open]
prepend_rules = [
	{ mime = "image/*", use = ["open", "wp", "reveal"] },
]
